import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'
const inter = Inter({ subsets: ["latin"] });
import Provider from "@/components/Provider";

export const metadata: Metadata = {
  title: "NoteIt",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <Provider>
          <body className={inter.className}>
            <main>
              {children}
            </main>
          </body>
        </Provider>
      </html>
    </ClerkProvider>
  );
}
